### ISSUE TITLE
Location Dropdown

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#13]
Can we add the Anywhere option in the  filter, for cases where location is not present?

**Comment by LieutenantRoger** [comment]
Currently, when we search the jobs based on location, we try to use the text to perform wildcard match with the jobLocation field.  

So if a jobLocation is null or empty, it won't match 'Anywhere' text as well.  

To show job with jobLocation is null or empty, user has to choose 'All' option, as if 'All' option is selected, we won't filter jobs based on location.
