### ISSUE TITLE
Sort Options : Ascending

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#14]
@Oanh-and-only-Oanh , Do we need the Ascending options? We dont have those options in Community app. 

<img width="291" alt="Screenshot 2021-10-05 at 9 50 43 AM" src="https://user-images.githubusercontent.com/58783823/135959701-54c6267b-1b52-4852-9f27-b72e12ccacd9.png">

**Comment by LieutenantRoger** [comment]
ok, will remove them to be align with comm app

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-10-11 at 2 51 26 PM" src="https://user-images.githubusercontent.com/58783823/136766041-d5ed41bf-bc9e-426f-bdaa-7e16ada3be33.png">
