### ISSUE TITLE
$ symbol not getting displayed if there is only max amount for a Gig

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#16]
Description:

$ symbol not getting displayed if there is only max amount for a Gig

![image](https://user-images.githubusercontent.com/55895538/136364801-0c1ba474-02c6-4ec5-b48c-c209a7107eb2.png)

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

![image](https://user-images.githubusercontent.com/55895538/136502072-d2826433-6e3a-4ecd-b62d-d4a69804f65c.png)

**Comment by SathyaJayabal** [comment]
No such example in prod.
