### ISSUE TITLE
Validation message if the Weekly payment From value is less than To value

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#17]
Description:
Validation message if the Weekly payment From value is less than To value

![image](https://user-images.githubusercontent.com/55895538/136365307-68191c29-ecc7-4689-a501-bae7d6399d09.png)

**Comment by LieutenantRoger** [comment]
We don't have a design regarding how to display the error message. Please clarify a bit how to handle this.  @SathyaJayabal @sandhiyakavi

**Comment by sandhiyakavi** [comment]
@LieutenantRoger 

1. Error message for the Weekly payment is still displaying even after clicking the Clear Filter button.

![image](https://user-images.githubusercontent.com/55895538/136503121-a33ae6a9-a8df-45aa-bf5d-f6abe8971930.png)

2. If we set some number in From field and try to edit the To field, we are not able to enter numbers and  it is populating with some default values 100, 1000, 10000 (even though we enter 200, 500 etc.)


https://user-images.githubusercontent.com/55895538/136504049-df996ef8-fab6-446a-9015-e6fa50d16851.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
![Uploading Screenshot 2021-10-11 at 3.01.52 PM.png…]()
