### ISSUE TITLE
Special gigs are displaying in all the pages

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#19]
Description:

Special gigs are displaying in all the pages

https://user-images.githubusercontent.com/55895538/136501731-a8a17e0d-ac3e-48ff-adf3-136cceb7778b.mp4

**Comment by SathyaJayabal** [comment]
verified on dev. special jobs are displayed only on the first page.
<img width="1440" alt="Screenshot 2021-10-11 at 8 46 20 AM" src="https://user-images.githubusercontent.com/58783823/136728495-9b56cfc1-c430-43ad-bfc9-ded0e824a80c.png">

**Comment by SathyaJayabal** [comment]
We dont have special gigs on production at present to  verify this scenario
