### ISSUE TITLE
Some skills listed under Skills/Technologies textbox are duplicated

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#20]
Description:

Some skills listed under Skills/Technologies textbox are duplicated. It's happening since the Skills from all the Skill providers are displayed. Filtering the skills by Skill provider ID/TaxonomyID will rectify the problem.

Note: The skills displayed in Taas app are filtered by the Skill provider 'Topcoder'

![image](https://user-images.githubusercontent.com/55895538/136520015-da21c249-6fee-4cc5-8ada-d83fc0888905.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-10-11 at 2 45 40 PM" src="https://user-images.githubusercontent.com/58783823/136765230-c7690446-664a-43d3-bd91-6452677abf23.png">
