### ISSUE TITLE
Normal jobs must exclude special jobs

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#22]
Normal jobs must exclude special jobs

**Comment by SathyaJayabal** [comment]
ref:https://topcoder.slack.com/archives/C020Y9C74G6/p1633719674132600?thread_ts=1633663594.125200&cid=C020Y9C74G6

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

Now,
1. If a job is only "showInHotList": true and is visible/not visible in the Hotlist (rectangular area) the job is shown along with the normal jobs too.
2. If a job is 'featured'=true, it is visible only in the special jobs (top of the listings) and is not duplicated.
