### ISSUE TITLE
The gigs-app/api/my-gigs/job endpoint must require externalId param

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#32]
The `gigs-app/api/my-gigs/job` endpoint must require `externalId` param

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/139629122-8fae25a2-87d7-4205-a2d1-07776e694da6.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 3 37 16 PM" src="https://user-images.githubusercontent.com/58783823/141279980-064151fd-67f7-4b7c-bbda-601502d89788.png">
