### ISSUE TITLE
hoursPerWeek field is missing in GET/job and GET/jobs endpoints

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#33]
Description:
hoursPerWeek field is missing in GET/job and GET/jobs endpoints

![image](https://user-images.githubusercontent.com/55895538/138666619-b2708cff-ee4a-483a-9269-d485eaade652.png)

![image](https://user-images.githubusercontent.com/55895538/138666521-310a9224-f415-4b74-85dc-5e9db868026b.png)

**Comment by sandhiyakavi** [comment]
@LieutenantRoger The hoursPerWeek field is displaying for GET/job now

![image](https://user-images.githubusercontent.com/55895538/139625426-f9133cae-6c26-4f98-8742-a986baa42796.png)

FYI This field is not displaying for GET/jobs (https://platform.topcoder-dev.com/gigs-app/api/my-gigs/jobs?page=1&perPage=100&sortBy=updatedAt&sortOrder=desc)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 3 41 58 PM" src="https://user-images.githubusercontent.com/58783823/141280222-9fec2c1b-3574-417c-8114-c95c6410ea99.png">
