### ISSUE TITLE
Message "YOU MUST BE A TOPCODER MEMBER TO APPLY!" is displayed even though the user is logged in

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#44]
Message "YOU MUST BE A TOPCODER MEMBER TO APPLY!" is displayed even though the user is logged in

On refreshing the page, the apply page is displayed.
<img width="1440" alt="Screenshot 2021-11-01 at 10 34 37 AM" src="https://user-images.githubusercontent.com/58783823/139624429-0a02cacd-35d8-489d-b41e-937fe68b5987.png">

https://user-images.githubusercontent.com/58783823/139624640-5df97769-ee7c-4cd6-b4ad-b15e8fb93573.mov

**Comment by SathyaJayabal** [comment]
Note: the profile api call is failing
https://platform.topcoder-dev.com/gigs-app/api/my-gigs/profile
<img width="1440" alt="Screenshot 2021-11-01 at 10 47 35 AM" src="https://user-images.githubusercontent.com/58783823/139625004-a3825786-205e-469f-9dd5-cb29f7cd5049.png">

**Comment by LieutenantRoger** [comment]
Yeah, if the profile API is failed, it makes sense to display above UI as if the current user is not having profile, we think he hasn't login, in another word, login user has to have a profile data. :) 

Let me try to reproduce this.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , logged in user necessarily will not have an rcrm profile. The rcrm profile will be created only after the first time the user applies to a job. But for users who have not applied to a job yet, we must display the apply page and not the login page.

To reproduce: Please register a new user and try to apply to any job.

**Comment by LieutenantRoger** [comment]
Here, I mean the `topcoder profile`, but not `rcrm profile`, so even new user should have topcoder profile, such firstName, lastName, email

**Comment by LieutenantRoger** [comment]
Please try more and see,  I actually found that Community-App is having similar behavior, see this snapshot:

https://monosnap.com/file/TS58sfaBmMaAdQqNi2dZcG1K9Neuco

**Comment by sandhiyakavi** [comment]
@LieutenantRoger @SathyaJayabal I tried to replicate this issue by creating a new user but didn't get this issue for that user 

But tried with another existing user (TCConncopilot) and got the message even though he is already logged in.

![image](https://user-images.githubusercontent.com/55895538/139803409-bcc3fa35-f1db-488b-8cf2-0d6b2a537bab.png)

**Comment by LieutenantRoger** [comment]
Can't reproduce on my side, TCConncopilot is working fine on my side, from your snapshot, it looks the profile API is failed.

https://monosnap.com/file/F9oyFBXYG5ujCAWrFtnLGttSdmDIQR

And I think it should be correct that the page shows you to login since we didn't get your profile back.

**Comment by LieutenantRoger** [comment]
Hmm, maybe we can display a text showing that getting profile error message here.

**Comment by vikasrohit** [comment]
Can we know the state of the nav bar from the gigs app? I mean if nav bar is showing member to be logged in and gigs app is showing member to be logged out, it would not be a good UX. If we can determine that nav bar is able to show logged in user (or if we can simply see cookies to determine a valid login session), and then profile api call fails to bring the profile of the user, we can show rather a generic error screen saying `Something bad happened. Please try again after some time or contact support if issue persists.`

**Comment by LieutenantRoger** [comment]
https://monosnap.com/file/2R771w45xOSbWUJnhDqFxb11EgpmXg

**Comment by LieutenantRoger** [comment]
>> Something bad happened. Please try again after some time or contact support if issue persists.

**Comment by LieutenantRoger** [comment]
Here is a simulation for it: https://monosnap.com/file/7jdQUfXogSN8m4nsj5eJKnw8n3nnh8

We can turning the UI later

**Comment by sandhiyakavi** [comment]
Not getting this issue now even with newly registered accounts. Gig Apply page is displaying now

**Comment by SathyaJayabal** [comment]
not seeing the issue on prod either
