### ISSUE TITLE
Validation error are displayed by default

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#45]
When a user clicks on apply button, the validation errors are displayed by default.
 the validation errors must be displayed 
expected : The validation errors must be displayed, only when the user clicks on the "Apply to this Job" Button. Validation should be similar to the gigs apply [age on community page.

https://user-images.githubusercontent.com/58783823/139624852-f3fef24a-7e2c-4ddc-82a2-106ad8bae299.mov

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Validation errors are not displayed by default now.


https://user-images.githubusercontent.com/55895538/139787090-a66e6062-8cad-4981-9261-3c44dc2ccaeb.mp4

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/141282678-7272f674-f608-4d24-967f-20ce67bd75bb.mov
