### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#47]
1. The validation messages font must be smaller, similar to community app.
<img width="1440" alt="Screenshot 2021-11-01 at 10 57 17 AM" src="https://user-images.githubusercontent.com/58783823/139625695-15f927d8-9ef7-4e26-9d4b-7a0d2cc23445.png">

2. Field label for city filed is not displayed.
<img width="1440" alt="Screenshot 2021-11-01 at 10 57 58 AM" src="https://user-images.githubusercontent.com/58783823/139625749-b42f616a-3f8e-4022-84f7-1f0d7a9aaf0c.png">

3. Links in the candidate terms popup must be in blue
<img width="1440" alt="Screenshot 2021-11-01 at 11 01 28 AM" src="https://user-images.githubusercontent.com/58783823/139626009-88fce0ca-c958-49bc-8aaf-a00c537c225e.png">

4. Default value for weekly pay expectation must be empty and not 0
<img width="635" alt="Screenshot 2021-11-01 at 11 07 10 AM" src="https://user-images.githubusercontent.com/58783823/139626367-ba2fa489-241b-46d7-be01-0a0778d97b1c.png">

5. Clicking on a field must change the field name to green, like on community app apply page

https://user-images.githubusercontent.com/58783823/139626643-f8605dc2-dcdf-4d6d-95e2-8a1bf186a5f0.mov

6. The asterisk (*) denoting a mandatory field is missing for the fields "first name" "last name" "email" and "phone".
<img width="1440" alt="Screenshot 2021-11-01 at 11 12 40 AM" src="https://user-images.githubusercontent.com/58783823/139626926-998bcfcd-5799-4f16-8af9-2709cfd2ad1b.png">

**Comment by LieutenantRoger** [comment]
4, Actually the community-app seems also displaying 0.  But I think make it empty is better.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

1. validation message font
![image](https://user-images.githubusercontent.com/55895538/139788852-7c2873a9-96e9-45e0-a544-a3ce14bf5e7e.png)

![image](https://user-images.githubusercontent.com/55895538/139788930-6639b9b2-a5de-4cc1-8b80-95cb02691d6f.png)

![image](https://user-images.githubusercontent.com/55895538/139789141-d467310f-9e2c-4516-b42a-79a22dba248a.png)

![image](https://user-images.githubusercontent.com/55895538/139789197-695c9034-cc9e-49cd-89b4-080c72c4658f.png)
![image](https://user-images.githubusercontent.com/55895538/139789791-960cc47d-964c-411e-82f8-e651c340cbae.png)
![image](https://user-images.githubusercontent.com/55895538/139789896-8f814ff0-7279-4fe6-8e1d-efd6075bdadd.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 4 04 18 PM" src="https://user-images.githubusercontent.com/58783823/141283925-e4667959-e0a5-4000-9128-83d1f0930d4d.png">
<img width="1440" alt="Screenshot 2021-11-11 at 4 05 10 PM" src="https://user-images.githubusercontent.com/58783823/141283951-c723bd69-1a1c-45c6-957f-1adb8b4fb272.png">
<img width="1440" alt="Screenshot 2021-11-11 at 4 06 09 PM" src="https://user-images.githubusercontent.com/58783823/141283959-fffdf1cf-2b6f-42de-bdef-ab057c29b984.png">
<img width="1440" alt="Screenshot 2021-11-11 at 4 06 45 PM" src="https://user-images.githubusercontent.com/58783823/141283963-8143f2d1-b85f-4e79-9a3c-7b7a5b264a47.png">
<img width="1440" alt="Screenshot 2021-11-11 at 4 07 28 PM" src="https://user-images.githubusercontent.com/58783823/141283969-a4f3c223-946d-44c0-acf8-a6e4dad892ed.png">
<img width="1440" alt="Screenshot 2021-11-11 at 4 08 01 PM" src="https://user-images.githubusercontent.com/58783823/141283974-739184e1-9147-4d57-ab82-34bac6db9f48.png">
