### ISSUE TITLE
The topcoder profile field should display the MFE profile

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#48]
The topcoder profile field should display the MFE profile
<img width="1440" alt="Screenshot 2021-11-01 at 11 16 54 AM" src="https://user-images.githubusercontent.com/58783823/139627432-83ac44e0-cf19-4d42-84b1-1f8970b3dfd3.png">

expected::
https://platform.topcoder-dev.com/profile/gigs_details

**Comment by sandhiyakavi** [comment]
Verified in Dev env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/139790212-e6fcdcd4-2d6a-4faf-9e60-aa8987c063b3.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 4 09 36 PM" src="https://user-images.githubusercontent.com/58783823/141284154-795de824-912c-47b4-8b7d-9e5a5bd6d725.png">
