### ISSUE TITLE
City and Country field data 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#49]
1. Go to the MFE gigs apply page. The city and country field data is loaded from member traits
<img width="1440" alt="Screenshot 2021-11-01 at 12 20 25 PM" src="https://user-images.githubusercontent.com/58783823/139632821-cdc051ed-b71f-4692-9dd6-bca22e6641a3.png">
2. Edit the fields to a different value and apply. These values are saved in rcrm.
<img width="1440" alt="Screenshot 2021-11-01 at 12 21 55 PM" src="https://user-images.githubusercontent.com/58783823/139632959-d6ffe95d-069e-4c1a-aaee-25a770836f52.png">
3. Apply to a different job, The city and country fields will be the old values, as they are loaded from member traits and the new values the user entered when applying to the job was written only to rcrm.

Is this behaviour ok?

https://user-images.githubusercontent.com/58783823/139633330-e94e7d15-1e1d-4dd3-b124-bd1d7c7a2c82.mov

**Comment by LieutenantRoger** [comment]
We currently are using the Community-App API directly, this behavior is same with Community-App. So I think it should be fine for now.

If we would like to persist the profile change in member's topcoder profile on Gig Apply page, we then will need to build dedicated API for it.

@Oanh-and-only-Oanh  Please advise

**Comment by Oanh-and-only-Oanh** [comment]
Please proceed with the the same behavior as with Community app.
