### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#50]
Description:

1. Validation message not showing for the mandatory fields "Tech Skills" and "How did you find out about Topcoder Gig Work?" 

![image](https://user-images.githubusercontent.com/55895538/139805445-18a6b7c7-5452-45cc-8f95-0922e9825c2c.png)

2. The text in the Topcoder profile textbox is not fully getting displayed.
![image](https://user-images.githubusercontent.com/55895538/139808038-b84d32ee-e324-4860-9594-922c02c3e3f3.png)

3. Displaying Empty brackets if Timezone is not specified for a gig. Should show "n/a" similar to the Community app.
![image](https://user-images.githubusercontent.com/55895538/139808730-1a7ad37c-b159-49a7-afab-a6aa05f1913a.png)

4. Getting validation message "Sum of all skill characters may not be greater than 100" for the Tech skills even though the number of skills is less than 100. 
![image](https://user-images.githubusercontent.com/55895538/139809258-f42826bd-d705-475f-a563-5fc4a0225083.png)

**Comment by SathyaJayabal** [comment]
@sandhiyakavi for the 4. it means the sum of skill characters

**Comment by LieutenantRoger** [comment]
1. Both are added as the required fields 
2. Hmm,  this seems due to the profile url is too long in MFE, but it is short in Community App. I think this is not an issue. See if the url is less, it will look like this: https://monosnap.com/file/w5PxNoSCLtkhHmkxUhTYiEpHcHPCx8
3. added "n/a" if the timezone is empty
4. Not an issue.

It's deploying, can validate about 10minutes

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/140015430-6a8cb6a9-94c7-4943-9e29-203cfa578ec1.png)

3. n/a displaying now.

![image](https://user-images.githubusercontent.com/55895538/140015709-194eae94-2ca9-42ec-b8b8-66b77c1467d9.png)

**Comment by SathyaJayabal** [comment]
verified on prod
1.
<img width="1440" alt="Screenshot 2021-11-11 at 4 11 06 PM" src="https://user-images.githubusercontent.com/58783823/141284781-6835f66f-8483-4cf6-a56b-80561f6909eb.png">

3. no example on prod
