### ISSUE TITLE
Not able to apply to Gig if the more than 7 Tech skills 

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#51]
Description:

Not able to apply to Gig if the more than 7 Tech skills 

![image](https://user-images.githubusercontent.com/55895538/139810824-97b5ebd3-5c01-4c73-8838-3da2024529a5.png)

https://user-images.githubusercontent.com/55895538/139810981-900b0869-d9a9-49e2-a026-2ace44ae5b45.mp4

**Comment by LieutenantRoger** [comment]
@sandhiyakavi  This is expected validation,

Please see Community-App: 

https://monosnap.com/file/vBzworoVRX8QYrcHhSNJvyJyQQSzAg

**Comment by sandhiyakavi** [comment]
@LieutenantRoger Yes, I compared it with Community app but I didn't get the validation message. Please see below screenshot.

![image](https://user-images.githubusercontent.com/55895538/139814143-acad6afd-e90b-4932-8339-e361cf2c2c51.png)

**Comment by LieutenantRoger** [comment]
Hmmm, maybe you need to select the exact same skill items, this field calculates the skills total characters in literal, it doesn't calculate how many skills you have selected.

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , the validation is the total sum of skill cahracters

**Comment by sandhiyakavi** [comment]
@LieutenantRoger @SathyaJayabal  Yes, If the same skills are added I am getting the validation message.

![image](https://user-images.githubusercontent.com/55895538/139817968-6ea66b42-81d4-4420-9202-1f284eac3601.png)

**Comment by sandhiyakavi** [comment]
Closing this issue as it is working as expected.
