### ISSUE TITLE
Minor UI issue: Two asterisk symbol displaying in the Country field

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#52]
Description:

Two asterisk symbol displaying in the Country field

![image](https://user-images.githubusercontent.com/55895538/140016526-33b075a2-9c94-493b-a70b-1ce062778a0e.png)

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/140031335-65bac3c9-0366-43d8-9da6-87940249fe99.png)

**Comment by SathyaJayabal** [comment]
No example on prod where user doesnt have a country.
