### ISSUE TITLE
Loading message is not displayed once the user applies for the gig

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#54]
Verify whether the loading message is displayed once the user applies for the gig (https://prnt.sc/1w7l5j8)

![bandicam 2021-11-08 16-36-31-859](https://user-images.githubusercontent.com/42398485/140731545-6ea8ed26-75e7-46d7-a398-2dc5acbf619f.jpg)

https://user-images.githubusercontent.com/42398485/140731572-10aa2daf-8009-41e1-808c-60a8051228cd.mp4

**Comment by codejamtc** [comment]
@LieutenantRoger Still I can see
![bandicam 2021-11-09 14-56-59-133](https://user-images.githubusercontent.com/42398485/140898147-585d25a0-5946-4b56-b0d1-8fe4761665bc.jpg)

**Comment by codejamtc** [comment]
![bandicam 2021-11-10 08-40-28-181](https://user-images.githubusercontent.com/42398485/141042712-a6d21ea1-5f59-4f67-ac9d-f7dffbf5924c.jpg)

https://user-images.githubusercontent.com/42398485/141042727-2785bef8-4111-49e6-82e5-2a77bb62a92f.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 5 54 39 PM" src="https://user-images.githubusercontent.com/58783823/141297672-0a3b59c3-3dab-43c2-b78a-172935139fa4.png">

https://user-images.githubusercontent.com/58783823/141297684-5f6a4597-c401-42a6-82c5-592ed55a3bbb.mov
