### ISSUE TITLE
User can apply to the same gig again and again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#55]
User can apply to the same gig again and again #55

1. Open the application and login
2. Open the gig listing page and click on the https://platform.topcoder-dev.com/earn/gigs/16333315679080010128hMz
3. Click Apply and complete the form and submit
4. When all completed click on the 'GO TO GIGS LIST' from the submit confirmation page
5. Click on the same gig
6. Click 'Apply to this Job' button and apply again

Gig: https://platform.topcoder-dev.com/earn/gigs/16333315679080010128hMz

https://user-images.githubusercontent.com/42398485/140732926-187e2818-4a3b-4657-89ea-002cfa637315.mp4

Gig: https://platform.topcoder-dev.com/earn/gigs/16333316170950010128cHl

https://user-images.githubusercontent.com/42398485/140731105-61294c74-8e5f-49fd-ad5a-ce2c7496ffd0.mp4

https://user-images.githubusercontent.com/42398485/140732044-591895fc-8caa-4eea-9f7b-ca540b41e735.mp4

![bandicam 2021-11-08 16-38-39-332](https://user-images.githubusercontent.com/42398485/140732064-3c06d89f-b4ec-4095-9e28-e2b053b1c4eb.jpg)

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , this is due to caching. Apply button will hide only when we refresh the page.

**Comment by LieutenantRoger** [comment]
Hmmm, good catch.  Just FYI, we support /gigs/{gigId}/apply to visit the gig apply page directly, so actually one member still is able to re-apply by using browser url directly to apply the same gig. 

But let me check the code and see to disable the cache of the gig detail information, so we prevent member from applying the same gig directly from UI.

**Comment by codejamtc** [comment]
@LieutenantRoger I can see the same behaviour when I follow below steps

- Open the application and login
- Open the gig listing page and click on the https://platform.topcoder-dev.com/earn/gigs/16333315679080010128hMz
- Click Apply and complete the form and submit
- When all completed click on the '< Back' from the submit confirmation page
- When we land on the gig details page
- Click 'Apply to this Job' button and apply again

https://user-images.githubusercontent.com/42398485/140985791-c6ab25da-3ebe-4ce4-90ed-5793cabc6fb5.mp4

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/141298478-1e83c43f-5d62-4c95-8709-d7e0a06f0a57.mov
