### ISSUE TITLE
The userhandle link of the Update Resume pop up should direct to the MFE user profile page

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-gigs-app#56]
Description:

The userhandle link of the Update Resume pop up should direct to the MFE user profile page.

It is currently directing to https://community-app.topcoder-dev.com/members/topacc_three but it should direct to https://platform.topcoder-dev.com/profile/topacc_three

![image (13)](https://user-images.githubusercontent.com/55895538/140731182-d61bc0c6-a8e3-419b-8be3-7fd630068ac2.png)

**Comment by codejamtc** [comment]
https://user-images.githubusercontent.com/42398485/140913009-c99c59b5-9a61-4888-9d81-310e7d0eeacc.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 4 20 16 PM" src="https://user-images.githubusercontent.com/58783823/141285663-307f7cea-0c10-4830-99be-c96dd9d148cd.png">
