### ISSUE TITLE
RESUME UPDATED! popup displayed again when we go to the My gig page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#58]
https://user-images.githubusercontent.com/42398485/140751632-10118a49-bdd7-478f-8be2-d6181fc696c6.mp4

**Comment by codejamtc** [comment]
https://user-images.githubusercontent.com/42398485/140904727-b49da310-f40f-4705-8bdc-18500db7ba18.mp4

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/141299130-aa576323-dab7-4b56-b2a8-09aeb4646377.mov
