### ISSUE TITLE
'Weekly Payment' filter is incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#59]
- Set the Weekly Payment = 500 - 1000 and apply

![bandicam 2021-11-08 19-22-20-564](https://user-images.githubusercontent.com/42398485/140753924-df4d9102-f72d-44cd-898e-c1a82a3f3115.jpg)

**Comment by LieutenantRoger** [comment]
This appears to be an issue of API. I'll fix the API firstly.

**Comment by LieutenantRoger** [comment]
This appears to be a bad data issue: https://prnt.sc/1yu82yq

See the job data, the maxSalary is 0 but the minSalary is 2000

I think we won't have such scenario in Prod data, https://www.topcoder.com/gigs

The frontend is displaying `2000+` if the max value is 0
