### ISSUE TITLE
Lastest gig is appearing way more down on the list

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#60]
https://platform.topcoder-dev.com/earn/gigs/16364324961930010128CeR

When I post and approve the gigi from the `recruitcrm` it is appearing way more down on the list

![bandicam 2021-11-09 10-18-34-630](https://user-images.githubusercontent.com/42398485/140864204-256594d3-b696-49a2-add2-1259e7ee7720.jpg)

**Comment by LieutenantRoger** [comment]
@codejamtc Please read this snapshot and see if it helps you understand it.

https://prnt.sc/1yujv0s

**Comment by codejamtc** [comment]
@LieutenantRoger Thanks for the information; I posted another one and it appears above the last one. As per the above comment I am closing this issue
