### ISSUE TITLE
The description posted via the TaaS is not appearing properly on the gig details page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#62]
https://platform.topcoder-dev.com/earn/gigs/16364343558620010128EOf

![bandicam 2021-11-09 10-48-46-667](https://user-images.githubusercontent.com/42398485/140866936-39cba062-c453-4e0d-b0a6-82e8f145f923.jpg)

https://platform.topcoder-dev.com/taas/myteams/18978/positions/08b91b83-539f-4200-b50f-49e09dd28e1c

![bandicam 2021-11-09 10-48-43-776](https://user-images.githubusercontent.com/42398485/140866938-7e44d801-4909-4d2c-a9e7-713e3896ad5f.jpg)

**Comment by SathyaJayabal** [comment]
A few styles are not rendered correctly , example:
<img width="1440" alt="Screenshot 2021-11-11 at 6 14 15 PM" src="https://user-images.githubusercontent.com/58783823/141300187-5a5ea3d6-1f4a-42ed-b559-d4d43f637601.png">

**Comment by LieutenantRoger** [comment]
https://monosnap.com/file/vnqzSylahTPM52b65k7mio5qcjL3NJ

**Comment by LieutenantRoger** [comment]
Testing jobId: 16343745034380010128XDA

**Comment by LieutenantRoger** [comment]
Fixed and Release to PROD
