### ISSUE TITLE
After applying for a gig from the ref link; and going to the my gig page won't show the gig on the list

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#63]
After applying for a gig from the ref link; and going to the my gig page won't show the gig on the list; user needs to alwasy refresh the page

https://user-images.githubusercontent.com/42398485/140869006-25cf7186-9689-4c16-bd5b-93f63ce20908.mp4

https://user-images.githubusercontent.com/42398485/140869017-c68e58a9-0762-46ff-9255-f424a420e7bd.mp4

**Comment by LieutenantRoger** [comment]
This is expected, after applying a job, the job won't show up in my-gigs immediately.  synch=true indicates the syncing process finished, and the job is ready to display on my-gigs: 

See the recording for it.   The syncing process will be faster in PROD, it seems to me the syncing process in DEV is a bit slow.

https://drive.google.com/file/d/1u1OI2JWmnNGuddk2HbFv-oQ-3lwU1M4f/view?usp=sharing

**Comment by SathyaJayabal** [comment]
verified on prod, job showing up in my gigs after applying
