### ISSUE TITLE
Ref Link is not displayed on the recruitcrm

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#64]
- Login as codejam_copilot
- Open a gig and get the ref code URL https://platform.topcoder-dev.com/earn/gigs/16364324961930010128CeR?referralId=j00qmq
- Login as another user and open the link https://platform.topcoder-dev.com/earn/gigs/16364324961930010128CeR?referralId=j00qmq
- Apply for the gig
- Go to recruitcrm
- Check the ref link https://app.recruitcrm.io/candidate-sequence/16364324961930010128CeR/assigned_candidates/0/16364364335590010128oFE

![bandicam 2021-11-09 11-51-49-396](https://user-images.githubusercontent.com/42398485/140873100-22e6a5f1-558a-4210-b31d-6105dab89f1c.jpg)

**Comment by codejamtc** [comment]
@LieutenantRoger

**Comment by codejamtc** [comment]
https://user-images.githubusercontent.com/42398485/140985248-e850d778-16b0-43c2-9161-3f10a0e4e209.mp4

![bandicam 2021-11-10 00-10-52-730](https://user-images.githubusercontent.com/42398485/140985270-c51632e3-3ace-46c9-8310-4ed74eac75d0.jpg)

**Comment by codejamtc** [comment]
- Using the `Your referral link` https://platform.topcoder-dev.com/earn/gigs?referralId=9gp7uw

https://user-images.githubusercontent.com/42398485/141048061-786d7c86-de8e-4c39-a255-94529a8d2e64.mp4

- Using the gig details page `referral link` https://platform.topcoder-dev.com/earn/gigs/16364343558620010128EOf?referralId=9gp7uw

https://user-images.githubusercontent.com/42398485/141048154-cbebcf28-9a4f-402a-9d84-10c07e386e8b.mp4

**Comment by codejamtc** [comment]
Yes, something is off now for new users. I tried with 2 new users and it didn't work
@picachui @LieutenantRoger

**Attempt 01:**

topcoderconnect+Manager@gmail.com > https://platform.topcoder-dev.com/earn/gigs/16359355488200010128Kef
Registered via mofexi9588@ecofreon.com

https://user-images.githubusercontent.com/42398485/141247466-6239a5a6-31b2-4462-8dac-e60549a72e98.mp4

**Attempt 02:**

topcoderconnect+Manager@gmail.com > https://platform.topcoder-dev.com/earn/gigs/16361305992890010128yTu
Registered via mofexi9589@mailinator.com

https://user-images.githubusercontent.com/42398485/141247495-95450be5-f3c9-4389-aeab-bdf80da1fd9f.mp4

**Comment by LieutenantRoger** [comment]
@SathyaJayabal @codejamtc  how is the label for this ticket

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , lets test on prod and close if its all good.

**Comment by LieutenantRoger** [comment]
ok, got it.

**Comment by SathyaJayabal** [comment]
referral data is not getting tracked when we apply to a job from MFE.

**Comment by SathyaJayabal** [comment]
verified on prod. referrals are getting tracked.
<img width="1440" alt="Screenshot 2021-11-12 at 4 50 07 PM" src="https://user-images.githubusercontent.com/58783823/141459117-2d7d00fd-e7fd-4f8b-9ac6-2a31e2884702.png">
![image (37)](https://user-images.githubusercontent.com/58783823/141459130-222d3b7a-b46f-4099-98d6-2dbb8c3aa8d1.png)
![image (38)](https://user-images.githubusercontent.com/58783823/141459343-56fb22e0-0ce9-49db-995c-c1f4480b1423.png)
