### ISSUE TITLE
"Application" typo in the submission confirmation page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/micro-frontends-gigs-app#66]
![bandicam 2021-11-10 17-46-13-084](https://user-images.githubusercontent.com/42398485/141111670-4048752c-61d0-48eb-a739-1652985b774c.jpg)

**Comment by codejamtc** [comment]
![bandicam 2021-11-10 22-02-17-522](https://user-images.githubusercontent.com/42398485/141153528-32de1e5e-9cdb-44a3-afab-91c0c52edbef.jpg)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-11 at 5 53 17 PM" src="https://user-images.githubusercontent.com/58783823/141297500-816f91c8-522b-4cde-9c7b-e154aefdc25d.png">
