### ISSUE TITLE
User is able to access a closed job using the job details page url

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-gigs-app#85]
User is able to access a closed job using the job details page url
Expected: User should see a message like "Job has been full-filled" like on community app, in case the job has been closed or otherwise unavailable.

Example:
https://platform.topcoder.com/earn/gigs/16300042451840013350bRI https://www.topcoder.com/gigs/16300042451840013350bRI

**Comment by LieutenantRoger** [comment]
In dev env, now any `not open job` or  `not active job` will display this screen.

![image](https://user-images.githubusercontent.com/2875203/154321970-65589e53-4658-4391-9c2e-a19789050e00.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2022-02-18 at 9 18 45 PM" src="https://user-images.githubusercontent.com/58783823/154715534-8dc28d3e-8ddf-4577-aab9-6998ae2de093.png">
