### ISSUE TITLE
MFE gig app is not showing any new jobs

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-gigs-app#96]
**Steps**
Add a new job from Taas app
Enable application form from RCRM
Go to EARN app >> Gigs (https://platform.topcoder-dev.com/earn/gigs?title=viewer&location=All&pay_min=0&pay_max=10000&by=date_added&order=desc&perpage=10&page=1)
Search for the above created job

Doesn't show any results

https://user-images.githubusercontent.com/4592712/158971155-fe9200a9-a562-45c5-aa21-29a08d50b140.mp4

**Comment by sandhiyakavi** [comment]
Update: The new jobs are now displaying in MFE gigs app , but the user applying from Gig page is not added to the job and the job is not listed in the My-gigs page also.
Also even though the user has already applied for previous gigs, it is not displaying so

![image](https://user-images.githubusercontent.com/55895538/159409443-c77c98f9-c58b-4432-a6d1-eb48330ed542.png)

**Comment by LieutenantRoger** [comment]
Yes, from the Error message, it said 401, let me double check the token, highly possible due to the token is changed in dev environment.  

So this is a dev only issue, in PROD it should work like before

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Issue is resolved.

![image](https://user-images.githubusercontent.com/55895538/159421796-c411fea6-3531-4700-a3a6-42c726f1f548.png)
![image](https://user-images.githubusercontent.com/55895538/159421857-e2a4d288-11b8-428b-b0ce-bfbdbc674958.png)
![image](https://user-images.githubusercontent.com/55895538/159421960-cd7d2fda-3dae-49c6-8b8d-cccc73abb3d7.png)
![image](https://user-images.githubusercontent.com/55895538/159422113-1693457c-6b07-4603-853e-2b57867ee203.png)
